server:
  port: 8090

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.2.90/magic-boot?rewriteBatchedStatements=true&useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
  config:
    import:
      - optional:classpath:application.yml

magic-api:
  resource:
    location: data/dongxinheping

forest:
  variables:
    aimsHost: 119.29.52.245:9002
    stationCode: 10001
    mixColor: CYAN
    controlDispatchAsync: false
  log-response-content: false

# 插件路径
plugin:
  auto-load: true
  auto-start: true
  signature-force-verify: false
