server:
  port: 8089

spring:
  datasource:
    username: magic
    password: Magic@2026

  config:
    import:
      - optional:classpath:application.yml

# 上传路径
upload:
  dir: ./uploads

# 插件路径
plugin:
  dir: ./plugins/
