<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.2</version>
        <relativePath/>
    </parent>

    <groupId>org.ssssssss</groupId>
    <artifactId>magic-boot</artifactId>
    <version>0.0.2</version>
    <packaging>pom</packaging>
    <name>magic-boot</name>
    <description>magic-boot</description>

    <modules>
        <module>magic-dependencies</module>
        <module>magic-api-parent</module>
        <module>magic-boot-plugins</module>
        <module>magic-editor</module>
        <module>magic-boot-master</module>
        <module>magic-plugins</module>
        <module>magic-plugins-demo</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- 引入依赖版本管理 -->
            <dependency>
                <groupId>org.ssssssss</groupId>
                <artifactId>magic-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
