<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.2</version>
        <relativePath/>
    </parent>

    <groupId>org.ssssssss</groupId>
    <artifactId>magic-boot</artifactId>
    <version>0.0.2</version>
    <packaging>pom</packaging>
    <name>magic-boot</name>
    <description>magic-boot</description>

    <modules>
        <module>magic-api-plugins</module>
        <module>magic-boot-master</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.release>17</maven.compiler.release>
        <magic-api.version>2.2.2</magic-api.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.ssssssss</groupId>
                <artifactId>magic-api</artifactId>
                <version>${magic-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ssssssss</groupId>
                <artifactId>magic-script</artifactId>
                <version>1.9.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
