{
  "properties" : { },
  "id" : "eb92d28985d74d0e888180a98e150f9e",
  "script" : null,
  "groupId" : "1828eba93a114c2f9f957e9cfc77258b",
  "name" : "查询任务列表",
  "createTime" : 1772682310657,
  "updateTime" : 1772782642378,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : "admin",
  "path" : "/list",
  "method" : "GET",
  "parameters" : [ ],
  "options" : [ ],
  "requestBody" : "",
  "headers" : [ ],
  "paths" : [ ],
  "responseBody" : "{\n    \"code\": 200,\n    \"message\": \"success\",\n    \"data\": \"Hello magic-api\",\n    \"timestamp\": 1772782640662,\n    \"executeTime\": 4\n}",
  "description" : "",
  "requestBodyDefinition" : null,
  "responseBodyDefinition" : null
}
================================
return 'Hello magic-api'