-- 用户ID与灯光颜色映射表
CREATE TABLE IF NOT EXISTS t_user_light_color (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
  color VARCHAR(16) NOT NULL COMMENT '灯光颜色(RED/GREEN/BLUE/YELLOW/CYAN)',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用:1启用 0停用',
  remark VARCHAR(255) NULL DEFAULT NULL COMMENT '备注',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_t_user_light_color_user_id (user_id),
  KEY idx_t_user_light_color_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户灯光颜色映射表';
