<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.ssssssss</groupId>
        <artifactId>magic-boot</artifactId>
        <version>0.0.2</version>
    </parent>

    <artifactId>magic-boot-plugins</artifactId>
    <version>2.2.2</version>
    <packaging>pom</packaging>
    <name>magic-boot-plugins</name>
    <description>auto generate http api</description>

    <modules>
        <module>magic-api-plugin-redis</module>
        <module>magic-api-plugin-job</module>
        <module>magic-api-plugin-liteflow</module>
        <module>magic-api-plugin-mqtt</module>
        <module>magic-api-plugin-springdoc</module>
        <module>magic-api-plugin-excel</module>
        <module>magic-editor</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.ssssssss</groupId>
            <artifactId>magic-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.ssssssss</groupId>
            <artifactId>magic-script</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>