{
  "properties" : { },
  "id" : "b411fce5b52748cca8ea77332d23f5a3",
  "script" : null,
  "groupId" : "dd1aa7ab04da4b30b39e28e1f47e164d",
  "name" : "testJob",
  "createTime" : 1772601042705,
  "updateTime" : 1772601089379,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : "admin",
  "path" : "/test",
  "cron" : "* * * * *",
  "enabled" : true,
  "description" : null
}
================================
import log

log.info("hello world")

return 'Hello magic-api-task'