{
  "properties" : { },
  "id" : "0b605de92ec34e76b3340c565c31f791",
  "script" : null,
  "groupId" : "4a3c0ad862bb4b5fb16c4c673b5a75a3",
  "name" : "测试",
  "createTime" : 1772601698095,
  "updateTime" : 1773637690217,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : "admin",
  "path" : "/test",
  "cron" : "0 * * * * ?",
  "enabled" : false,
  "description" : "这是一个测试任务1",
  "params" : "{\r\n    \"s\":1\r\n}",
  "misfirePolicy" : "IGNORE",
  "concurrent" : false,
  "dependsOn" : null,
  "maxRetry" : 0,
  "timeout" : 1,
  "jobType" : "clazz",
  "clazz" : "org.ssssssss.magicapi.job.quartz.TestJob"
}
================================
return ""
