{
  "properties" : { },
  "id" : "f8476380035841abb4a1153398ade316",
  "script" : null,
  "groupId" : "999006442fb54aebbb2015e4a23bdba8",
  "name" : "定时同步article数据",
  "createTime" : 1776664436822,
  "updateTime" : 1776664607628,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : "admin",
  "path" : "/articles",
  "cron" : "0 */5 * * *",
  "enabled" : false,
  "description" : "",
  "params" : "",
  "misfirePolicy" : "SMART",
  "concurrent" : false,
  "dependsOn" : null,
  "maxRetry" : 0,
  "timeout" : 0,
  "jobType" : "script",
  "clazz" : null
}
================================
return 'Hello magic-api-job'