plugin.id=dongxinheping-plugin
plugin.name=Dongxinheping PDA Plugin
plugin.description=Dongxinheping PDA static pages
plugin.class=org.ssssssss.magicboot.dongxinheping.DongxinhepingPlugin
plugin.version=1.0.0
plugin.provider=MagicBoot Team
