{
  "properties" : { },
  "id" : "ecf2ae687a364778968da09e5993290d",
  "script" : null,
  "groupId" : "c81a0bceabdf4f2a965b46fdc22e3288",
  "name" : "测试串行编排",
  "createTime" : 1772617604111,
  "updateTime" : 1772677348013,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : "admin",
  "path" : "/cxbp",
  "enabled" : true,
  "chainId" : "chain1",
  "namespace" : null,
  "route" : null,
  "description" : "12",
  "params" : "{\r\n    \"a\": 1\r\n}",
  "el" : null
}
================================
// LiteFlow EL 规则表达式
THEN(
    groovy1
)